name: client
description: BUILD-er Mechanical friend
version: 1.0.0+6
environment:
  sdk: ">=2.17.0-266.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^4.8.0
  firebase_analytics: #^9.1.9
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1 #2.9.0 #^1.17.1
  # firebase_core_platform_interface: ^4.6.0 #4.5.1
  firebase_core_platform_interface: ^4.8.0
  firebase_crashlytics: #^2.8.1
  firebase_storage: #^10.2.17
  # firebase_auth_desktop: ^1.0.0
  # firebase_core_desktop: ^1.0.0
  flutter_map: ^4.0.0
  vector_map_tiles: ^4.0.0
  provider: ^6.0.3
  flutter_map_marker_cluster: ^1.0.1
  location: ^4.4.0
  flutter_map_location_marker: ^6.0.0
  location_picker_flutter_map: ^1.1.5
  dotted_border: ^2.0.0+2
  flutter_svg: ^2.0.6
  shared_preferences: ^2.0.15
  http: ^0.13.4
  latlong2: ^0.8.1
  # shopping_cart: 0.0.2
  overlay_loading_progress: 1.0.1
  # image_pickers: 2.0.3+1
  fluttertoast: ^8.1.1
  image_picker: ^0.8.7+5
  permission_handler: 10.2.0
  device_info: ^2.0.3
  responsive_sizer: ^3.0.8
  font_awesome_flutter: ^10.1.0
  flutter_rating_bar: ^4.0.1
  ymchat_flutter: ^2.3.5
  flutter_chat_ui: ^1.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/res/

  fonts:
    - family: ProjectBuilder
      fonts:
        - asset: assets/fonts/app.ttf
    - family: SF Pro Rounded
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded/Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Rounded/Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Rounded/Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Rounded/Regular.otf
          weight: 400

