import 'package:client/core/models/notifications.dart';
import 'package:client/core/models/portfolio.dart';
import 'package:client/core/models/products.dart';
import 'package:client/core/models/user.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';

class Var {
  static const e = "";
  static const s = " ";
  static const q = "?";
  static const na = "N/A";
  static const appName = "ProjectBuilder";
  static const appLogo = "assets/images/res/builder-logo.png";
  static const builder = "BUILD-ER";
  static const ok = "OK";
  static const cancel = "Cancel";
  static const yes = "Yes";
  static const no = "No";
  static const logout = "LOGOUT";
  static const logoutMsg = "Do you wish to log out?";
  static const defaultFont = "SF Pro Rounded";
  static const ecommerce = "E-COMMERCE";
  static const about = "ABOUT";
  static const profile = "PROFILE";
  static const userPlaceholder = "assets/images/res/user-placeholder.png";
  static const userPlaceholderNet = "https://firebasestorage.googleapis.com/v0/b/nustar-resort-app-92c7c.appspot.com/o/user-placeholder.png?alt=media&token=270f28f1-c9be-4283-a58e-46792053027f";
  static const noImageAvailable = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/No_image_available.svg/2048px-No_image_available.svg.png";
  static const camera = "CAMERA";
  static const gallery = "GALLERY";
  static const imagesRef = "IMAGES/";
  static const permitRef = "PERMIT/";
  static const uploading = "Uploading ";
  static const uploadingPaused = "Upload is paused.";
  static const uploadingCanceled = "Upload was canceled.";
  static const uploadingError = "Uploading file error.";
  static const uploadingCompleted = "File upload successfully completed!";
  static const complete = "complete.";
  static const users = "users";
  static const jpeg = ".jpeg";
  static const uploadFromGallery = "Upload Image from Gallery";
  static const permit = "PERMIT";
  static const license = "LICENSE";
  static const dti = "DTI";
  static const sec = "SEC";
  static const upload = "Upload";
  static const createClientAccount = "Create New Client Account";
  static const createContractorAccount = "Create New Contractor Account";
  static const enterName = "Enter your Name";
  static const enterEmail = "Enter your Email";
  static const enterPassword = "Enter your Password";
  static const confirmPassword = "Confirm your Password";
  static const enterPhone = "Enter your Phone Number";
  static const enterCompany = "Enter your Company Name";
  static const enterAddress = "Enter your Address";
  static const enterBriefDetails = "Enter your Brief Details";
  static const selectLocation = "SELECT YOUR LOCATION";
  static const register = "REGISTER";
  static const login = "LOGIN";
  static const forgotPassword = "Forgot password?";
  static const validID = "Valid ID";
  static const noImageReceived = "Image upload cancelled!";
  static const passwordMismatched = "Password Mismatched! Please re-enter your password correctly.";
  static const admin = "admin";
  static const client = "client";
  static const contractor = "Contractor";
  static const capsContractor = "CONTRACTOR";
  static const home = "HOME";
  static const aboutBuilder = "Build-er is a smartphone application that connects you with nearby, reputable, and reliable contractors in any field to help build your ideas and visions turn into reality. Its purpose is to eliminate fraud and assure the legitimacy of your chosen contractor. Build-er also provides the client with a free online consultation and price estimation. Aside from that, Build-er offers affordable construction tools, equipment, and materials through its e-commerce shopping feature.";
  static const services = "OUR SERVICES";
  static const servicesInfo = "Offers construction tools, equipment, and materials for users to select and buy their desired products; this also offers service - deep-cleaning and plumbing services. This application ensures the authenticity of the users' reviews, contractors and/or suppliers in order to prevent fraudulent circumstances.";
  static const stanleyLogo = "assets/images/res/stanley-logo.png";
  static const dewaltLogo = "assets/images/res/dewalt-logo.png";
  static const makitaLogo = "assets/images/res/makita-logo.jpg";
  static const partners = "OUR PARTNERS";
  static const asecLogo = "assets/images/res/asec-logo.jpg";
  static const asecBuilding = "assets/images/res/asec-building.jpg";
  static const ckiLogo = "assets/images/res/cki-logo.jpg";
  static const ckiRestau = "assets/images/res/cki-restaurants.jpg";
  static const datemLogo = "assets/images/res/datem-logo.jpg";
  static const datemBuilding = "assets/images/res/datem-buildings.png";
  static const ffLogo = "assets/images/res/ff-logo.png";
  static const ffFishport = "assets/images/res/ff-fishport.jpg";
  static const asdecLogo = "assets/images/res/asdec-logo.png";
  static const asdecSmCoast = "assets/images/res/asdec-sm-coast.png";
  static const monolithLogo = "assets/images/res/monolith-logo.png";
  static const monolithMoaArena = "assets/images/res/monolith-moa-arena.jpg";
  static const lightBg = "assets/images/res/light-bg.jpg";
  static const asdec = "Asdec Builders Corporation";
  static const asec = "Asec Development and Construction Corporation";
  static const cki = "CKI Builders Engineering Services";
  static const datem = "DATEM Incorporated";
  static const ffCruz = "F.F. Cruz Co., Inc.";
  static const monolithConstruction = "Monolith Construction Development Corporation";
  static const portfolio = "PORTFOLIO";
  static const notification = "NOTIFICATION";
  static const user = "USERS";
  static const products = "PRODUCTS";
  static const materialIcons = "MaterialIcons";
  static const faq = "FAQ";
  static const locator = "LOCATOR";
  static const privacyPolicy = "PRIVACY POLICY";
  static const copyright = "2023 BUILD-er.\nALL RIGHTS RESERVED.";
  static const welcome = "Welcome, ";
  static const featureNotAvailable = "Sorry, this feature isn't available right now.";
  static const findNearbyContractors = "Find nearby Contractors";
  static const nearby = "Nearby";
  static const productDetails = "PRODUCT DETAILS";
  static const goBack = "GO BACK";
  static const addCart = "ADD TO CART";
  static const ecommerceTagLine1 = "A Summer Surprise\n";
  static const ecommerceTagLine2 = "Mega Sale 50% off!";
  static const ourProducts = "Our Products";
  static const contractorHome = "CONTRACTOR HOME";
  static const startupBg = "assets/images/res/launch-bg.jpg";
  static const splashBG = "assets/images/res/splash-bg.png";
  static const addProduct = "+ ADD NEW PRODUCT";
  static const productDescription = "Product Description";
  static const productName = "Product Name";
  static const productImage = "Product Image";
  static const productPrice = "Product Price";
  static const productS = "products";
  static const clientS = "clients";
  static const productCode = "PRDBLDR";
  static const productSuccess = "Product Successfully Saved!";
  static const portfolioSuccess = "Portfolio Successfully Saved!";
  static const unableSave = "Unable to save!";
  static const submit = "SUBMIT";
  static const selectCategory = "Please select Product Category";
  static const productCategory = "Product Category";
  static const adminProducts = "ADMIN PRODUCTS";
  static const viewProduct = "VIEW PRODUCT";
  static const constructionMaterials = "Construction Materials";
  static const constructionTools = "Construction Tools";
  static const userLists = "USER LISTS";
  static const viewUser = "VIEW USER";
  static const emailAddress = "EMAIL ADDRESS";
  static const userID = "USER ID";
  static const phoneNumber = "PHONE NUMBER";
  static const address = "ADDRESS";
  static const verifyUser = "VERIFY THIS USER";
  static const userVerified = "USER VERIFIED";
  static const verifyThisUserMsg = "Do you want to verify this user?";
  static const contractorRequests = "CONTRACTOR REQUESTS";
  static const clientRequests = "CLIENT REQUESTS";
  static const roles = "roles";
  static const contractorRequestTab = "ContractorRequestsTab";
  static const clientRequestTab = "ClientRequestsTab";
  static const userIsNowUpdated = "Successfully updated! This user is now approved!";
  static const isUserVerified = "isUserVerified";
  static const userCancelled = "User cancelled!";
  static const userNotVerified = "User not Verified.";
  static const verifiedUser = "Verified User and approved by Admin.";
  static const uid = "uid";
  static const notVerifiedUseMsg = "This user is not yet verified! Waiting for Approval by the Administrator for you to access the other pages from the BUILD-ER app. Thank you for your understanding!";
  static const warning = "Warning!";
  static const builderTagline = '"Building your visions, Creating Reality"';
  static const keyFeatures = "KEY FEATURES";
  static const keyFeaturesImg = "assets/images/res/key-features.png";
  static const reviewsImg = "assets/images/res/reviews-bg.png";
  static const partnersImg = "assets/images/res/partners-bg.png";
  static const addPortfolio = "ADD NEW PORTFOLIO";
  static const companyName = "COMPANY NAME";
  static const briefDetails = "BRIEF DETAILS OF THE COMPANY";
  static const feedback = "FEEDBACK";
  static const enter = "ENTER ";
  static const companyLogo = "COMPANY LOGO";
  static const previousCompany = "PREVIOUS COMPANY";
  static const portfolioCode = "PRTFL";
  static const notifCode = "NTF";
  static const ratings = "RATINGS";
  static const refresh = "REFRESH";
  static const splash = "Splashscreen";
  static const noAvailablePortfolio = "No available/submitted portfolios...";
  // static const aaa = "aaa";

  static const String userPendingForVerification = "DPL1W";
  static const String adminApprovedUserVerification = "VML2RW";
  static const String adminStatus = "PFA9R";
  
  static var appTitle = "";
  static var activePage = "";
  static var activeUserRole = "";
  static var previousRoute = "";
  static var selectedContractorId = "";
  static var categories = [
    constructionMaterials,
    constructionTools,
  ];
  static bool userIsVerified = false;
  static bool userReadsNearbyContractors = false;

  static Product? product;
  static List<Product> productLists = [];
  static List<Portfolio> portfolioLists = [];
  static List<Portfolio> contractorNearbyPortfolioLists = [];
  static List<Portfolio> selectedContractorPortfolio = [];
  static List<UserModel> usersLists = [];
  static List<UserModel> filteredClientUsers = [];
  static List<UserModel> filteredContractorUsers = [];
  static List<UserModel> nearbyContractorUsers = [];
  static List<Notifications> notifLists = [];

  static charRandomizer() {
    final now = DateTime.now();
    return now.microsecondsSinceEpoch.toString();
  }

}