import 'package:client/core/models/products.dart';

class Var {
  static const na = "N/A";
  static const appName = "ProjectBuilder";
  static const appLogo = "assets/images/res/builder-logo.png";
  static const builder = "BUILD-ER";
  static const ok = "OK";
  static const cancel = "Cancel";
  static const yes = "Yes";
  static const no = "No";
  static const logout = "LOGOUT";
  static const logoutMsg = "Do you wish to log out?";
  static const defaultFont = "SF Pro Rounded";
  static const ecommerce = "E-COMMERCE";
  static const about = "ABOUT";
  static const profile = "PROFILE";
  static const userPlaceholder = "assets/images/res/user-placeholder.png";
  // static const userPlaceholder = "https://firebasestorage.googleapis.com/v0/b/nustar-resort-app-92c7c.appspot.com/o/user-placeholder.png?alt=media&token=270f28f1-c9be-4283-a58e-46792053027f";
  static const noImageAvailable = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/No_image_available.svg/2048px-No_image_available.svg.png";
  static const camera = "CAMERA";
  static const gallery = "GALLERY";
  static const imagesRef = "IMAGES/";
  static const permitRef = "PERMIT/";
  static const uploading = "Uploading ";
  static const uploadingPaused = "Upload is paused.";
  static const uploadingCanceled = "Upload was canceled.";
  static const uploadingError = "Uploading file error.";
  static const uploadingCompleted = "File upload successfully completed!";
  static const complete = "complete.";
  static const users = "users";
  static const jpeg = ".jpeg";
  static const uploadFromGallery = "Upload Image from Gallery";
  static const permit = "PERMIT";
  static const license = "LICENSE";
  static const dti = "DTI";
  static const sec = "SEC";
  static const upload = "Upload";
  static const createClientAccount = "Create New Client Account";
  static const createContractorAccount = "Create New Contractor Account";
  static const enterName = "Enter your Name";
  static const enterEmail = "Enter your Email";
  static const enterPassword = "Enter your Password";
  static const confirmPassword = "Confirm your Password";
  static const enterPhone = "Enter your Phone Number";
  static const enterCompany = "Enter your Company Name";
  static const enterAddress = "Enter your Address";
  static const selectLocation = "SELECT YOUR LOCATION";
  static const register = "REGISTER";
  static const login = "LOGIN";
  static const forgotPassword = "Forgot password?";
  static const validID = "Valid ID";
  static const noImageReceived = "No Image Received!";
  static const passwordMismatched = "Password Mismatched! Please re-enter your password correctly.";
  static const admin = "admin";
  static const client = "client";
  static const contractor = "Contractor";
  static const capsContractor = "CONTRACTOR";
  static const home = "HOME";
  static const aboutBuilder = "Build-er is a smartphone application that connects you with nearby, reputable, and reliable contractors in any field to help build your ideas and visions turn into reality. Its purpose is to eliminate fraud and assure the legitimacy of your chosen contractor. Build-er also provides the client with a free online consultation and price estimation. Aside from that, Build-er offers affordable construction tools, equipment, and materials through its e-commerce shopping feature.";
  static const services = "OUR SERVICES";
  static const servicesInfo = "Offers construction tools, equipment, and materials for users to select and buy their desired products; this also offers service - deep-cleaning and plumbing services. This application ensures the authenticity of the users' reviews, contractors and/or suppliers in order to prevent fraudulent circumstances.";
  static const stanleyLogo = "assets/images/res/stanley-logo.png";
  static const dewaltLogo = "assets/images/res/dewalt-logo.png";
  static const makitaLogo = "assets/images/res/makita-logo.jpg";
  static const partners = "OUR PARTNERS";
  static const asecLogo = "assets/images/res/asec-logo.jpg";
  static const asecBuilding = "assets/images/res/asec-building.jpg";
  static const ckiLogo = "assets/images/res/cki-logo.jpg";
  static const ckiRestau = "assets/images/res/cki-restaurants.jpg";
  static const datemLogo = "assets/images/res/datem-logo.jpg";
  static const datemBuilding = "assets/images/res/datem-buildings.png";
  static const ffLogo = "assets/images/res/ff-logo.png";
  static const ffFishport = "assets/images/res/ff-fishport.jpg";
  static const asdecLogo = "assets/images/res/asdec-logo.png";
  static const asdecSmCoast = "assets/images/res/asdec-sm-coast.png";
  static const monolithLogo = "assets/images/res/monolith-logo.png";
  static const monolithMoaArena = "assets/images/res/monolith-moa-arena.jpg";
  static const asdec = "Asdec Builders Corporation";
  static const asec = "Asec Development and Construction Corporation";
  static const cki = "CKI Builders Engineering Services";
  static const datem = "DATEM Incorporated";
  static const ffCruz = "F.F. Cruz Co., Inc.";
  static const monolithConstruction = "Monolith Construction Development Corporation";
  static const portfolio = "PORTFOLIO";
  static const user = "USERS";
  static const products = "PRODUCTS";
  static const materialIcons = "MaterialIcons";
  static const faq = "FAQ";
  static const locator = "LOCATOR";
  static const privacyPolicy = "PRIVACY POLICY";
  static const copyright = "2023 BUILD-er.\nALL RIGHTS RESERVED.";
  static const welcome = "Welcome, ";
  static const featureNotAvailable = "Sorry, this feature isn't available right now.";
  static const findNearbyContractors = "Find nearby Contractors";
  static const productDetails = "PRODUCT DETAILS";
  static const goBack = "GO BACK";
  static const addCart = "ADD TO CART";
  static const ecommerceTagLine1 = "A Summer Surpise\n";
  static const ecommerceTagLine2 = "Mega Sale 50% off!";
  static const ourProducts = "Our Products";
  static const contractorHome = "CONTRACTOR HOME";
  // static const aaa = "aaa";
  
  static var activePage = "";
  static var activeUserRole = "";
  static var previousRoute = "";
  static Product? product;

  static charRandomizer() {
    final now = DateTime.now();
    return now.microsecondsSinceEpoch.toString();
  }
}