// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDpWnjmqp_0DN7XgLQowFSlJXQjnga2B40",
    authDomain: "build-er.firebaseapp.com",
    projectId: "build-er",
    storageBucket: "build-er.appspot.com",
    messagingSenderId: "168271902222",
    appId: "1:168271902222:web:6090706ff8a6b4ae6dee5f"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpWnjmqp_0DN7XgLQowFSlJXQjnga2B40',
    appId: "1:168271902222:web:6090706ff8a6b4ae6dee5f",
    messagingSenderId: '168271902222',
    projectId: "build-er",
    storageBucket: "build-er.appspot.com",
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyDpWnjmqp_0DN7XgLQowFSlJXQjnga2B40",
    authDomain: "build-er.firebaseapp.com",
    projectId: "build-er",
    storageBucket: "build-er.appspot.com",
    messagingSenderId: "168271902222",
    appId: "1:168271902222:web:6090706ff8a6b4ae6dee5f"
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: "AIzaSyDpWnjmqp_0DN7XgLQowFSlJXQjnga2B40",
    authDomain: "build-er.firebaseapp.com",
    projectId: "build-er",
    storageBucket: "build-er.appspot.com",
    messagingSenderId: "168271902222",
    appId: "1:168271902222:web:6090706ff8a6b4ae6dee5f"
  );
}
